/* DO NOT EDIT THIS FILE - it is machine generated */
#ifndef UM_ANDROID_LOG
#define UM_ANDROID_LOG

#include <jni.h>
#include <android/log.h>
#include <string>

using namespace std;

/**
 * Android Log Class
 */
class  UMLog
{
public:
	 UMLog();
	~ UMLog();
	static void D(char const* tag, char const* msg);
	static void V(char const* tag, char const* msg);
	static void I(char const* tag, char const* msg);
	static void E(char const* tag, char const* msg);
};


#endif
