/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "platform/android/jni/JniHelper.h"
#include <android/log.h>
#include "cocos2d.h"
#include "UmengSocial/CCUMTypeDef.h"
#include <string>
#include <vector>

/* Header for class com_umeng_social_CCUMSocialController */
USING_NS_CC;
using namespace std;

#ifndef _Included_com_umeng_social_CCUMSocialController
#define _Included_com_umeng_social_CCUMSocialController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_umeng_social_CCUMSocialController
 * Method:    OnAuthorizeStart
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_umeng_social_CCUMSocialController_OnAuthorizeStart
  (JNIEnv *, jclass, jint);


/*
 * Class:     com_umeng_social_CCUMSocialController
 * Method:    OnAuthorizeComplete
 * Signature: ([Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_umeng_social_CCUMSocialController_OnAuthorizeComplete
  (JNIEnv *, jclass, jint, jint, jobjectArray);

/*
 * Class:     com_umeng_social_CCUMSocialController
 * Method:    OnShareStart
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_umeng_social_CCUMSocialController_OnShareStart
  (JNIEnv *, jclass);

/*
 * Class:     com_umeng_social_CCUMSocialController
 * Method:    OnShareComplete
 * Signature: (IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_umeng_social_CCUMSocialController_OnShareComplete
  (JNIEnv *, jclass, jint, jint, jstring);

// /*
//  * Class:     com_umeng_social_CCUMSocialController
//  * Method:    getCocos2dxScrShot
//  * Signature: ()Ljava/lang/String;
//  */
// JNIEXPORT jstring JNICALL Java_com_umeng_social_CCUMSocialController_getCocos2dxScrShot
//   (JNIEnv *, jclass);

// /*
//  * Class:     com_umeng_social_CCUMSocialController
//  * Method:    onShakeComplete
//  * Signature: ()V
//  */
// JNIEXPORT void JNICALL Java_com_umeng_social_CCUMSocialController_onShakeComplete
//   (JNIEnv *, jclass);
    


/*
*
*/
bool getMethod(JniMethodInfo &mi, const char *methodName, const char *paramCode);

/*
 * 设置友盟app key
 */
void setUmengAppkey(const char* appkey);
        
/*
* 对某平台进行授权
*
*/
void doAuthorize(int platform, AuthEventHandler callback);
/*
* 删除某平台的授权信息
*
*/
void deletePlatformAuthorization(int platform, AuthEventHandler callback);
    
/*
* 判断某平台是否已经授权
*
*/
bool isPlatformAuthorized(int platform);
    
/*
* 打开分享面板
*
*/
void doOpenShare(bool registerListener, ShareEventHandler callback);
    
/*
* 底层分享
*
*/
void doDirectShare(int platform, ShareEventHandler callback);

/*
*
*/
void releaseMethod(JniMethodInfo &mi);

/*
* 设置要分享的文字内容
*
*/
void setShareTextContent(const char* text);
/*
*设置要分享的图片的本地路径
*
*/
void setShareImageName(const char* pathOrUrl);
/*
* 设置要分享的图片的url
*
*/
// void setShareImagesUrl(const char* url);

    
    
// /*
// * 添加平台支持
// *
// */
// void doSupportPlatform(int platform, const char* appkey, const char* targetUrl);
    
/*
* 设置平台顺序呢
*
*/
void setSocialPlatforms(vector<int>* platforms);
// /*
// * 移除某些平台
// *
// */
// void removePlatforms(int platforms[]);
// /*
// * 清空sdk
// */
// void cleanupSDK();

jstring charToJstring(JNIEnv* env,const char* text) ;

    
#ifdef __cplusplus
}
#endif
#endif
