/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "platform/android/jni/JniHelper.h"
#include <android/log.h>
#include "cocos2d.h"
#include "UmengSocial/CCUMTypeDef.h"
#include <string>

/* Header for class com_umeng_social_CCUMSocialController */
USING_NS_CC;
using namespace std;

#ifndef _Included_com_umeng_social_CCUMSocialController
#define _Included_com_umeng_social_CCUMSocialController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_umeng_social_CCUMSocialController
 * Method:    OnAuthorizeStart
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_umeng_social_CCUMSocialController_OnAuthorizeStart
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_umeng_social_CCUMSocialController
 * Method:    OnAuthorizeError
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_umeng_social_CCUMSocialController_OnAuthorizeError
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_umeng_social_CCUMSocialController
 * Method:    OnAuthorizeCancel
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_umeng_social_CCUMSocialController_OnAuthorizeCancel
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_umeng_social_CCUMSocialController
 * Method:    OnAuthorizeComplete
 * Signature: ([Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_umeng_social_CCUMSocialController_OnAuthorizeComplete
  (JNIEnv *, jclass, jobjectArray, jstring);

/*
 * Class:     com_umeng_social_CCUMSocialController
 * Method:    OnShareStart
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_umeng_social_CCUMSocialController_OnShareStart
  (JNIEnv *, jclass);

/*
 * Class:     com_umeng_social_CCUMSocialController
 * Method:    OnShareComplete
 * Signature: (Ljava/lang/String;ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_umeng_social_CCUMSocialController_OnShareComplete
  (JNIEnv *, jclass, jstring, jint, jstring);

/*
 * Class:     com_umeng_social_CCUMSocialController
 * Method:    getCocos2dxScrShot
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_umeng_social_CCUMSocialController_getCocos2dxScrShot
  (JNIEnv *, jclass);

/*
 * Class:     com_umeng_social_CCUMSocialController
 * Method:    onShakeComplete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_umeng_social_CCUMSocialController_onShakeComplete
  (JNIEnv *, jclass);
    


/*
*
*/
bool getMethod(JniMethodInfo &mi, const char *methodName, const char *paramCode);
    
/*
*
*/
void releaseMethod(JniMethodInfo &mi);

/*
* 设置要分享的文字内容
*
*/
void setShareTextContent(const char* text);
/*
*设置要分享的图片的本地路径
*
*/
void setShareImageFilePath(const char* path);
/*
* 设置要分享的图片的url
*
*/
void setShareImagesUrl(const char* url);
    
/*
* 对某平台进行授权
*
*/
void doAuthorize(const char* platform, AuthEventHandler callback);
/*
* 删除某平台的授权信息
*
*/
void deletePlatformAuthorization(const char* platform, AuthEventHandler callback);
    
/*
* 判断某平台是否已经授权
*
*/
bool isPlatformAuthorized(const char* platform);
    
/*
* 打开分享面板
*
*/
void doOpenShare(bool registerListener, ShareEventHandler callback);
    
/*
* 底层分享
*
*/
void doDirectShare(const char* platform, ShareEventHandler callback);
    
    
/*
* 添加平台支持
*
*/
void doSupportPlatform(const char* platform, const char* appkey, const char* targetUrl);
    
/*
* 设置平台顺序呢
*
*/
void setPlatformsOrder(string platformOrders[]);
/*
* 移除某些平台
*
*/
void removePlatforms(string platforms[]);
/*
* 清空sdk
*/
void cleanupSDK();
    

    
#ifdef __cplusplus
}
#endif
#endif
